language: generic
include:
  - os: linux
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - debootstrap
          - genisoimage
          - p7zip-full
          - squashfs-tools
          - ubuntu-dev-tools
          - dpkg-dev
          - debhelper
          - fakeroot
          - devscripts

sudo: required

git:
  depth: 22

script:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - chmod +x ./build.sh
  - ./build.sh |& tee log.txt

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: fJmkIPnBSbitOnsJaXd0+EsJvCGMrV98abFDF1JyEpfs972ZhNg4n3bwUre3WgfU0S7gEQUlPBdnnro0k/R3uvvq2kxcBjlDF1slTU28UrPB3/Z638AwHeA088+cgmB9wYluDGILzXepvZ0e1/LD8klMzlZBuTlaxkRExTtA8mFotwWVX428cdyR3hnrORbRHyiRAPM392CZhCrgatD8KMKeIkTXzOzCyoOa2+/qS+kMBPK+xa7mkAGlOVuoPdleqh1tLLwmROaiZPvj/5N0N/4qnONUquFlzi4z9dhXjDx5Gbl1x/2bD3PJWpsps8lGTFRlSaRBtgsgHKz/h1+3O+w+QbIfZ/1w0ezolac09l7xMULoF2/WPqwILZdStFqa7GtfVtGV3yvGOF1ooziQp15RYLwWux+7tsm/TBcrtn1HMSSAYzyfOb0nl1J59gCwW8hosL5xj7MZpHP0BdvMk9p9NZTSC5piCR9f7b1GGs2Dz9qp3v3IL+G71nD+mQVj0dd9Dj40uRo/ugec15H/MI7jS6LMHcuMRN81A1ZlMaBZBZE8dIrUq8lxpmzjCZK/s6jm5yecmonDswfFxt96vxrNfhZAPQmMyAD3dzBmul8n7Ql1KiW4fZuPtexHI0zLdmhJakj+OH6LGaPIVtBngyq3w1FIBQtwfR9VTo9EEuE=
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      all_branches: true

after_deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/releases_maintainer.sh; fi'
  - cd scripts && ./mail.py
  
after_failure:
  - cd scripts && ./mail-fail.py
